apiVersion: v1
kind: Service
metadata:
  name: "console"
  labels: {{- include "minio-operator.labels" . | nindent 4 }}
spec:
  ports:
  - name: http
    port: 9090
  - name: https
    port: 9443
  selector: {{- include "minio-operator.console-selectorLabels" . | nindent 4 }}

---

apiVersion: v1
kind: Service
metadata:
  name: "console-nodeport"
spec:
  type: NodePort
  selector:
    {{- include "minio-operator.console-selectorLabels" . | nindent 4 }}
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 9443
      targetPort: 9443
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 31443
